[build-system]
requires        =["setuptools>=61.0"]
build-backend   = "setuptools.build_meta"

[project]
name            = "RenesSQLiteHelper"
version         = "2026.9.18"
description     = "René's minimal wrapper around Python's sqlite3 module"
readme          = "README.md"
license         = "MIT"
requires-python = ">=3.8"
authors         = [ {name = "René Nyffenegger"} ]
classifiers     = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Repository = "https://github.com/ReneNyffenegger/py-RenesSQLiteHelper"
Homepage   = "https://renenyffenegger.ch/notes/development/languages/Python/standard-library/sqlite3/RenesSQLiteHelper"
